# Generated by Django 4.2 on 2023-04-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('protagonists', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='movie_posters/')),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('coming-up', 'Coming Up'), ('starting', 'Starting'), ('running', 'Running'), ('finished', 'Finished')], max_length=10)),
                ('ranking', models.IntegerField(default=0)),
            ],
        ),
    ]
